***
## Task 1: Create Directory Structure 

#### Using the command line, create a directory (that is, a folder) named data at the root of your repository. Inside data, create two subdirectories: timestamps and weather.

- Open WSL Terminal: Launch your WSL terminal. You can do this by searching for "WSL" or "Ubuntu" in your start menu.
- Navigate to the Root of Your Repository: Use the cd command to change your directory to the root of your repository. For example, if your repository is located in ~/projects/24-25-Computer-Infrastructure
- Create the data Directory: Use the mkdir command to create a directory named data: mkdir data
- Navigate into the data Directory: Change your directory to the newly created data directory: cd data
- Create the timestamps and weather Subdirectories: Use the mkdir command to create the timestamps and weather subdirectories: mkdir timestamps weather

***
## Task 2: Timestamps

#### Navigate to the data/timestamps directory. Use the date command to output the current date and time, appending the output to a file named now.txt. Make sure to use the >> operator to append (not overwrite) the file. Repeat this step ten times, then use the more command to verify that now.txt has the expected content.

- The easiest way is just type the following command into your code terminal: for i in {1..10}; do date >> now.txt; sleep 1; done

- Keep in mind that >> add new line all the time that the script run the code and > overwrite the previous data.

***
## Task 3: Formatting Timestamps

#### Run the date command again, but this time format the output using YYYYmmdd_HHMMSS (e.g., 20261114_130003 for 1:00:03 PM on November 14, 2026). Refer to the date man page (using man date) for more formatting options. (Press q to exit the man page). Append the formatted output to a file named formatted.txt.

- Run the date command with the specified format and append the output to formatted.txt: date +"%Y%m%d_%H%M%S" >> formatted.txt
- Verify the content of formatted.txt: cat formatted.txt

***
## Task 4: Create Timestamped Files

#### Use the touch command to create an empty file with a name in the YYYYmmdd_HHMMSS.txt format. You can achieve this by embedding your date command in backticks ` into the touch command. You should no longer use redirection (>>) in this step.

- Use the touch command with the date command embedded in backticks: touch `date +"%Y%m%d_%H%M%S"`.txt

 The touch command creates an empty file. By embedding the date command within backticks (`), the current date and time are formatted using the YYYYmmdd_HHMMSS pattern and used as the file name. For example, if the current date and time are November 14, 2026, at 1:00:03 PM, the command will create a file named 20261114_130003.txt.

***
## Task 5: Download Today's Weather Data

#### Change to the data/weather directory. Download the latest weather data for the Athenry weather station from Met Eireann using wget. Use the -O <filename> option to save the file as weather.json. The data can be found at this URL: https://prodapi.metweb.ie/observations/athenry/today.

- Download the weather data using wget and save it as weather.json: wget -O weather.json https://prodapi.metweb.ie/observations/athenry/today

The wget command downloads the data from the specified URL. The -O weather.json option saves the downloaded data to a file named weather.json.

***
## Task 6: Timestamp the Data


#### Modify the command from Task 5 to save the downloaded file with a timestamped name in the format YYYYmmdd_HHMMSS.json

- Download the weather data using wget and save it with a timestamped name: wget -O `date +"%Y%m%d_%H%M%S"`.json https://prodapi.metweb.ie/observations/athenry/today

- The wget command downloads the data from the specified URL. The -O option specifies the output file name. By embedding the date command within backticks (`), the current date and time are formatted using the YYYYmmdd_HHMMSS pattern and used as the file name. For example, if the current date and time are November 14, 2026, at 1:00:03 PM, the command will save the file as 20261114_130003.json.

***
## Task 7: Write the Script

#### Write a bash script called weather.sh in the root of your repository. This script should automate the process from Task 6, saving the weather data to the data/weather directory. Make the script executable and test it by running it.

- Create and open the weather.sh script using a text editor: cd /path/to/your/repository
nano weather.sh
- Add the following content to weather.sh: #!/bin/bash
- Navigate to the data/weather directory: cd data/weather
- Download the weather data and save it with a timestamped name: wget -O `date +"%Y%m%d_%H%M%S"`.json https://prodapi.metweb.ie/observations/athenry/today
- Save and close the script: In nano, press Ctrl+O to save the file, then press Enter. Press Ctrl+X to exit the editor.
- Make the script executable: chmod +x weather.sh
- Test the script by running it: ./weather.sh

***
## Task 8: Notebook

#### Create a notebook called weather.ipynb at the root of your repository. In this notebook, write a brief report explaining how you completed Tasks 1 to 7. Provide short descriptions of the commands used in each task and explain their role in completing the tasks.

##### Task 1: Create Directories
To create the required directories, we used the `mkdir` command to create the `data` directory and the `timestamps` and `weather` subdirectories inside `data`.

##### Task 2: Record Timestamps
To record the current date and time into `now.txt` ten times, we used the `date` command in a loop. The `date >> now.txt` command appends the current date and time to `now.txt`.

##### Task 3: Formatting Timestamps
To format the date and time using `YYYYmmdd_HHMMSS` and append it to `formatted.txt`, we used the `date +"%Y%m%d_%H%M%S"` command to format the current date and time, and the `>> formatted.txt` command to append the formatted output to `formatted.txt`.

##### Task 4: Create Timestamped File
To create an empty file with a timestamped name, we used the `touch` command with the `date` command embedded. The `touch \`date +"%Y%m%d_%H%M%S"\`.txt` command creates an empty file with a timestamped name.

##### Task 5: Download Weather Data
To download the latest weather data and save it as `weather.json`, we used the `wget` command with the `-O` option to specify the output file name.

##### Task 6: Timestamped Weather Data
To save the downloaded weather data with a timestamped name, we modified the `wget` command to include the `date` command embedded. The `wget -O \`date +"%Y%m%d_%H%M%S"\`.json` command downloads the data and saves it with a timestamped name.

##### Task 7: Automate with Script
To automate the process, we created a bash script `weather.sh` that navigates to the `data/weather` directory and downloads the weather data with a timestamped name. We made the script executable using the `chmod +x` command and ran it to download the weather data.

***
## Task 9 pandas

#### In your weather.ipynb notebook, use the pandas function read_json() to load in any one of the weather data files you have downloaded with your script. Examine and summarize the data. Use the information provided data.gov.ie to write a short explanation of what the data set contains.

### Weather Analisis

In [8]:
import pandas as pd

### Collecting Data

the following code output the filname used to store the data file
```bash
date +"%Y%m%d_%H%M%S"_athenry.json
```

### Analysing the Data

In [9]:
#read the data
df = pd.read_json('data/weather/20241113_195237_athenry.json')

In [10]:
#show
df.head()

,name,temperature,symbol,weatherDescription,text,windSpeed,windGust,cardinalWindDirection,windDirection,humidity,rainfall,pressure,dayName,date,reportTime
0,Athenry,6.0,46n,Light rain,"""Light rain """,4,-,E,90,99,0.01,1041.0,Wednesday,2024-11-13,00:00
1,Athenry,5.0,05n,Rain showers,"""Rain shower""",4,-,NE,45,99,0.01,1040.0,Wednesday,2024-11-13,01:00
2,Athenry,5.0,05n,Rain showers,"""Rain shower""",2,-,N,0,99,0.10,1040.0,Wednesday,2024-11-13,02:00
3,Athenry,6.0,15n,Fog / Mist,"""Fog thinning""",4,-,SE,135,99,0.00,1040.0,Wednesday,2024-11-13,03:00
4,Athenry,6.0,15n,Fog / Mist,"""Fog thinning""",4,-,E,90,99,0.00,1040.0,Wednesday,2024-11-13,04:00

In [11]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   20 non-null     object
 1   temperature            14 non-null     float64
 2   symbol                 20 non-null     object
 3   weatherDescription     20 non-null     object
 4   text                   20 non-null     object
 5   windSpeed              20 non-null     object
 6   windGust               20 non-null     object
 7   cardinalWindDirection  20 non-null     object
 8   windDirection          20 non-null     int64
 9   humidity               20 non-null     int64
 10  rainfall               12 non-null     float64
 11  pressure               14 non-null     float64
 12  dayName                20 non-null     object
 13  date                   20 non-null     datetime64[ns]
 14  reportTime             20 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(9)
memory usage: 2.5+ KB

,temperature,windDirection,humidity,rainfall,pressure,date
count,14.000000,20.000000,20.00000,12.000000,14.000000,20
mean,6.071429,81.000000,29.75000,0.026667,1039.857143,2024-11-13 00:00:00
min,4.000000,0.000000,-99.00000,0.000000,1039.000000,2024-11-13 00:00:00
25%,5.000000,0.000000,-99.00000,0.000000,1040.000000,2024-11-13 00:00:00
50%,5.500000,67.500000,99.00000,0.000000,1040.000000,2024-11-13 00:00:00
75%,6.000000,135.000000,99.00000,0.032500,1040.000000,2024-11-13 00:00:00
max,9.000000,225.000000,100.00000,0.100000,1041.000000,2024-11-13 00:00:00
std,1.685426,87.111544,96.93127,0.044381,0.534522,NaN

### Explanation of the Data Set: 

The weather data set contains observations from the Athenry weather station provided by Met Eireann. The data includes various meteorological parameters such as temperature, humidity, wind speed, wind direction, and atmospheric pressure. Each observation is timestamped, providing a record of the weather conditions at specific times throughout the day.

According to data.gov.ie, the data set includes the following fields:

- temperature: The air temperature in degrees Celsius.
- humidity: The relative humidity as a percentage.
- wind_speed: The wind speed in meters per second.
- wind_direction: The wind direction in degrees.
- pressure: The atmospheric pressure in hectopascals (hPa).
- timestamp: The date and time of the observation.

### End
***